config/routes.rb
PharmaPortal::Application.routes.draw do
  get "search/Search"
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}, via: [:get,:post]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :transfer_of_value
  resources :disputes
  root to: "sessions#new"
  match '/dashboard',to: "static_pages#dashboard", via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/recipients', to: 'transfer_of_value#recipients', :via => :post
  match '/spends', to: 'transfer_of_value#spends', :via => :post
  match '/party',to: 'transfer_of_value#party', :via => :post
  match '/product', to: 'transfer_of_value#product', :via => :post
  match '/updates',to: 'transfer_of_value#updates',:via => :post

  match "/search", to: 'search#Search', :as => :search, :via => :get
  match "/searchDisputes", to: 'search#SearchDisputes',:as => :searchDisputes,:via => :get

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def Search
  	start=Date.strptime params[:Start], '%m-%d-%Y' unless params[:Start]==""
	  ends=Date.strptime params[:End], '%m-%d-%Y' unless params[:End]==""
  	userType=params[:UserType] unless params[:UserType]=="All"
  	state=params[:State] unless params[:State]=="All"
  	activity=params[:ActivityType] unless params[:ActivityType]=="All"
  	detail=params[:DetailType] unless params[:DetailType]=="All"
  	nature=params[:NatureOfPayment] unless params[:NatureOfPayment]=="All"
  	@result=TransferOfValue.joins('inner join "recipient_amounts" on "transfer_of_values"."id"="recipient_amounts"."AmountID" inner join "users" on "recipient_amounts"."RecipientID"="users"."id"').where('(? is null or "transfer_of_values"."DateofPayment" >= ? ) and (? is null or "transfer_of_values"."DateofPayment" <= ?) and (? is null or "users"."userType"=?) and (? is null or "users"."state"=?) and (? is null or "transfer_of_values"."ActivityType"=?) and (? is null or "transfer_of_values"."DetailType"=?) and (? is null or "transfer_of_values"."NatureofPayment"=?)',start,start,ends,ends,userType,userType,state,state,activity,activity,detail,detail,nature,nature)
    @start= params[:Start]
    @ends= params[:End]
    @userType=params[:UserType] 
    @state=params[:State] 
    @activity=params[:ActivityType] 
    @detail=params[:DetailType] 
    @nature=params[:NatureOfPayment] 
  end

  def SearchDisputes
  	start=Date.strptime params[:Start], '%m-%d-%Y' unless params[:Start]==""
  	ends=Date.strptime params[:End], '%m-%d-%Y' unless params[:End]==""
	  status=params[:status] unless params[:status]=="All"
	  exceptions=params[:Exception] unless params[:Exception]=="All"
	  @dispute=Dispute.joins('inner join "transfer_of_values" on "disputes"."AmountID" = "transfer_of_values"."id"').where('(? is null or "disputes"."DisputeDate" >= ? ) and (? is null or "disputes"."DisputeDate" <= ?) and (? is null or "disputes"."Status" = ? ) and (? is null or "disputes"."Description"=?)',start,start,ends,ends,status,status,exceptions,exceptions)
    @start=params[:Start]
    @ends=params[:End]
    @status=params[:status]
    @exceptions=params[:Exception]
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/Search.html.erb
<table>
	<tr>
		<td width="80%" style ="vertical-align:top">
			<h2>Results</h2>
			<table class="tablestyle" >
				<tr>
					<th>
						Spend Id
					</th>
					<th>
						Transfer of Value Date
					</th>
					<th>
						Amount
					</th>
					<th>
						Number of Payments
					</th>
					<th>
						Nature of Payment
					</th>
				</tr>
				<% if @result.nil? %>
				<tr>
					<td>
						No Spends found.
					</td>
				</tr>
				<% else %>
					<% @result.each do |s| %>
						<tr>
							<td>
								<%= link_to s.id,s, style: "color: #0099cc;font-weight:bold" %>
							</td>
							<td>
								<% if !s.DateofPayment.nil? %>
									<%= s.DateofPayment.to_time.strftime('%b %d,%Y') %>
								<% end %>
							</td>
							<td>
								<%= s.totalAmount %>
							</td>
							<td>
								<%= s.numberofPayment %>
							</td>
							<td>
								<%= s.NatureofPayment %>
							</td>
						</tr>
					<% end %>
				<% end %>
			</table>
		</td>
		<td width="20%">
			<form action='<%= search_path %>' method='get'>
			<div class="box1">
			<h2>Filter</h2>
			<table >
				<tr width="100%">
					<td>
						Start Date <input type="text" name="Start" id="TxtBx_StartDate" style="width:65px" value="<%= @start %>">
					</td>
					<td>
						End Date <input type="text" name="End" id="TxtBx_EndDate" style="width:65px" value="<%= @ends %>">
					</td>
				</tr>
				<tr>
					<td>
					</td>
				</tr>
				<tr width="100%">
					<td>
						<br/>
						<hr/>
						Recipent Type
						<%= select_tag "userType", options_for_select(["All","Physician","Hospital"],@userType) %>
					</td>
				</tr>
				<tr width="100%">
					<td>
						<br/>
						<hr/>
						Recipent State
						<%= select_tag "State", options_for_select([
                                "All",
                                "Alabama AL",
                                "Alaska AK",
                                "Arizona AZ",
                                "Arkansas AR",
                                "California CA",
                                "Colorado CO",
                                "Connecticut CT",
                                "Delaware DE",
                                "Florida FL",
                                "Georgia GA",
                                "Hawaii HI",
                                "Idaho ID",
                                "Illinois IL",
                                "Indiana IN",
                                "Iowa IA",
                                "Kansas KS",
                                "Kentucky KY",
                                "Louisiana LA",
                                "Maine ME",
                                "Maryland MD",
                                "Massachusetts MA",
                                "Michigan MI",
                                "Minnesota MN",
                                "Mississippi MS",
                                "Missouri MO",
                                "Montana MT",
                                "Nebraska NE",
                                "Nevada NV",
                                "New Hampshire NH",
                                "New Jersey NJ",
                                "New Mexico NM",
                                "New York NY",
                                "North Carolina NC",
                                "North Dakota ND",
                                "Ohio OH",
                                "Oklahoma OK",
                                "Oregon OR",
                                "Pennsylvania PA",
                                "Rhode Island RI",
                                "South Carolina SC",
                                "South Dakota SD",
                                "Tennessee TN",
                                "Texas TX",
                                "Utah UT",
                                "Vermont VT",
                                "Virginia VA",
                                "Washington WA",
                                "West Virginia WV",
                                "Wisconsin WI",
                                "Wyoming WY"], @state) %>
					</td>
				</tr>
				<tr width="100%">
					<td>
						<br/>
						<hr/>
						Spend Activity Type
						<%= select_tag "ActivityType", options_for_select(["All","Call","Advisory Board"], @activity) %>
					</td>
				</tr>
				<tr width="100%">
					<td>
						<br/>
						<hr/>
						Spend Detail Type
						<%= select_tag "DetailType", options_for_select(["All","Lunch","Travel","Souvenir","Meal","Contracted Fee"], @detail) %>
					</td>
				</tr>
				<tr width="100%">
					<td>
						<br/>
						<hr/>
						Business Purpose
						<%= select_tag "NatureOfPayment", options_for_select(["All","Promotion"],@nature),{:onchange=>'$(this.form).submit();' } %>
					</td>
				</tr>
			</table>
			<table>
				<tr>
					<td>
						<input type="submit" value="Filter" style=" width:40px;height:35px;background-color:#181818;border-radius:5px; display:inline-block; color: white; font-size:10px;  text-decoration: none; margin-left: 5%; margin-top: 15px; margin-bottom: 15px; text-align:center;">
					</td>
					<td>
					</td>
				</tr>
			</table>
			</form>
		</td>
	</tr>
</table>
<script type="text/javascript">
	$('#TxtBx_StartDate').datepicker({
		buttonImageOnly: true,
		buttonImage: 'calendar.jpg',
		dateFormat: 'mm-dd-yy'
	});
	$('#TxtBx_EndDate').datepicker({
		buttonImageOnly: true,
		buttonImage: 'calendar.jpg',
		dateFormat: 'mm-dd-yy'
	});
</script>

app/views/search/SearchDisputes.html.erb
<table>
	<tr>
		<td width="80%" style ="vertical-align:top">
			<h2>Results</h2>
			<table class="tablestyle" >
				<tr>
					<th>
						Case Id
					</th>
					<th>
						Spend Id
					</th>
					<th>
						status
					</th>
					<th>
						Description
					</th>
					<th>
						Created
					</th>
					<th>
					</th>		
				</tr>
				<% if @dispute.nil? %>
				<tr>
					<td>
						No Dispute is raised.
					</td>
				</tr>
				<% else %>
					<% @dispute.each do |d| %>
					<tr>
						<td>
							<%= d.id %>
						</td>
						<td>
							<%= link_to d.AmountID, transfer_of_value_path(d.AmountID), style: "color:#0099cc;font-weight:bold" %>
						</td>
						<td>
							<%= d.Status %>
						</td>
						<td>
							<%= d.Description %>
						</td>
						<td>
							<% if !d.DisputeDate.nil? %>
								<%= d.DisputeDate.to_time.strftime('%b %d,%Y') %>
							<% end %>
						</td>
						<td width="20%">
							<% if d.Status == "Dispute" %>
								<%= link_to "Correct Spend",edit_transfer_of_value_path(d.AmountID), style: "color:#0099cc;font-weight:bold" %>
							<% end %>
						</td>			
					</tr>
					<% end %>
				<% end %>
			</table>
		</td>
		<td width="20%">
			<form action='<%= searchDisputes_path %>' method='get'>
				<div class="box1">
				<h2>Filter</h2>
				<table >
					<tr width="100%">
						
					</tr>
						<td>
							Start Date <input type="text" name="Start" id="TxtBx_StartDate" style="width:65px" value="<%= @start %>">
						</td>
						<td>
							End Date <input type="text" name="End" id="TxtBx_EndDate" style="width:65px" value="<%= @ends %>">
						</td>
					<tr>
						<td>
							<br/>
							<hr/>
							Case Status
							<%= select_tag "status", options_for_select(["Open","Dispute","Resolved"],@status) %>
						</td>
					</tr>
					<tr>
						<td>
							<br/>
							<hr/>							
							Exception
							<%= select_tag "Exception", options_for_select(["All"],@exceptions) %>
						</td>
					</tr>
				</table>
				<table>
					<tr>
						<td>
							<input type="submit" value="Filter" style=" width:40px;height:35px;background-color:#181818;border-radius:5px; display:inline-block; color: white; font-size:10px;  text-decoration: none; margin-left: 5%; margin-top: 15px; margin-bottom: 15px; text-align:center;">
						</td>
						<td>
						</td>
					</tr>
				</table>
			</form>
		</td>
	</tr>
</table>
<script type="text/javascript">
	$('#TxtBx_StartDate').datepicker({
		buttonImageOnly: true,
		buttonImage: 'calendar.jpg',
		dateFormat: 'mm-dd-yy'
	});
	$('#TxtBx_EndDate').datepicker({
		buttonImageOnly: true,
		buttonImage: 'calendar.jpg',
		dateFormat: 'mm-dd-yy'
	});
</script>