config/routes.rb
PharmaPortal::Application.routes.draw do
  get "search/Search"
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}, via: [:get,:post]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :transfer_of_value
  resources :disputes
  root to: "sessions#new"
  match '/dashboard',to: "static_pages#dashboard", via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/recipients', to: 'transfer_of_value#recipients', :via => :post
  match '/spends', to: 'transfer_of_value#spends', :via => :post
  match '/party',to: 'transfer_of_value#party', :via => :post
  match '/product', to: 'transfer_of_value#product', :via => :post
  match '/updates',to: 'transfer_of_value#updates',:via => :post

  match "/search", to: 'search#Search', :as => :search, :via => :get
  match "/searchDisputes", to: 'search#SearchDisputes',:as => :searchDisputes,:via => :get

end

app/models/spend.rb
class Spend < ActiveRecord::Base
end

app/controllers/spends_controller.rb
class SpendsController < ApplicationController
  def new
  end

  def edit
    @spends=TransferOfValue.find(params[:id])
  end

  def index
  	@spend=TransferOfValue.all
  end

  def show
  	@spends=TransferOfValue.find(params[:id])
  end
end

app/helpers/spends_helper.rb
module SpendsHelper
end

app/views/spends/edit.html.erb
<div class="box1">
	<h2>Spends</h2>
	<table>
		<tr>
			<td>
				Start Date <input type="text" id="TxtBx_StartDate" style="width:65px">
			</td>
			<td>
				&nbsp;&nbsp;&nbsp;End Date <input type="text" id="TxtBx_EndDate" style="width:65px">
			</td>
		</tr>
	</table>
	<table>
		<tr>
			<td>
				Recipent Category
				<select>
					<option value="All">All</option>
				</select>
			</td>
			<td>
				&nbsp;&nbsp;&nbsp;Recipent Type
				<select>
					<option value="All">All</option>
				</select>
			</td>
			<td>
				&nbsp;&nbsp;&nbsp;Recipent State
				<%= select_tag :State, options_for_select([
                                "All",
                                "Alabama AL",
                                "Alaska AK",
                                "Arizona AZ",
                                "Arkansas AR",
                                "California CA",
                                "Colorado CO",
                                "Connecticut CT",
                                "Delaware DE",
                                "Florida FL",
                                "Georgia GA",
                                "Hawaii HI",
                                "Idaho ID",
                                "Illinois IL",
                                "Indiana IN",
                                "Iowa IA",
                                "Kansas KS",
                                "Kentucky KY",
                                "Louisiana LA",
                                "Maine ME",
                                "Maryland MD",
                                "Massachusetts MA",
                                "Michigan MI",
                                "Minnesota MN",
                                "Mississippi MS",
                                "Missouri MO",
                                "Montana MT",
                                "Nebraska NE",
                                "Nevada NV",
                                "New Hampshire NH",
                                "New Jersey NJ",
                                "New Mexico NM",
                                "New York NY",
                                "North Carolina NC",
                                "North Dakota ND",
                                "Ohio OH",
                                "Oklahoma OK",
                                "Oregon OR",
                                "Pennsylvania PA",
                                "Rhode Island RI",
                                "South Carolina SC",
                                "South Dakota SD",
                                "Tennessee TN",
                                "Texas TX",
                                "Utah UT",
                                "Vermont VT",
                                "Virginia VA",
                                "Washington WA",
                                "West Virginia WV",
                                "Wisconsin WI",
                                "Wyoming WY" ]),:style => "width:154px" %>
			</td>
		</tr>
	</table>
	<table>
		<tr>
			<td>
				Spend Activity Type
				<select>
					<option value="All">All</option>
					<option value="Call">Call</option>
					<option value="Advisory Board">Advisory Board</option>
				</select>
			</td>
			<td>
				&nbsp;&nbsp;&nbsp;Spend Detail Type
				<select>
					<option value="All">All</option>
					<option value="Lunch">Lunch</option>
					<option value="Travel">Travel</option>
					<option value="Souvenir">Souvenir</option>
					<option value="Meal">Meal</option>
					<option value="Contracted Fee">Contracted Fee</option>
				</select>
			</td>
		</tr>
	</table>
	<table>
		<tr>
			<td>
				Business Purpose
				<select>
					<option value="All">All</option>
					<option vlaue="Promotion">Promotion</option>
				</select>
			</td>
			<td>
			</td>
		</tr>
	</table>
	<table>
		<tr>
			<td>
				<input type="button" id="submit" value="Filter" style=" width:40px;height:35px;background-color:#181818;border-radius:5px; display:inline-block; color: white; font-size:10px;  text-decoration: none; margin-left: 5%; margin-top: 15px; margin-bottom: 15px; text-align:center;">
			</td>
			<td>
			</td>
		</tr>
	</table>
</div>
<br/>

<div class="box1">
	<%= form_for(@spends) do |f| %>
	<h2>Spend Description</h2>
	&nbsp;&nbsp;&nbsp;
	<b style="font-size:14px">
		Amount: 
	</b>
	<p>
		&nbsp;&nbsp;&nbsp;
		<%= f.text_field :Amount %>
	</p>
	&nbsp;&nbsp;&nbsp;
	<b style="font-size:14px">
		Spend Activity: 
	</b>
	<p>
		&nbsp;&nbsp;&nbsp;
		<%= f.text_field :SpendActivity %>
	</p>
	&nbsp;&nbsp;&nbsp;
	<b style="font-size:14px">
		Spend Detail: 
	</b>
	<p>
		&nbsp;&nbsp;&nbsp;
		<%= f.text_field :SpendDetail %>
	</p>
	&nbsp;&nbsp;&nbsp;
	<b style="font-size:14px">
		Business Purpose: 
	</b>
	<p>
		&nbsp;&nbsp;&nbsp;
		<%= f.text_field :BusinessPurpose %>
	</p>
	&nbsp;&nbsp;&nbsp;
	<b style="font-size:14px">
		Spend Description: 
	</b>
	<p>
		&nbsp;&nbsp;&nbsp;
		<%= f.text_field :spend_description %>
	</p>
	&nbsp;&nbsp;&nbsp;
	<b style="font-size:14px">
		Spend Date: 
	</b>
	<p>
		&nbsp;&nbsp;&nbsp;
		<%= f.text_field :Date %>
	</p>
	&nbsp;&nbsp;&nbsp;
	<b style="font-size:14px">
		Payment Date: 
	</b>
	<p>
		&nbsp;&nbsp;&nbsp;
		<%= f.text_field :payment_date %>
	</p>
	&nbsp;&nbsp;&nbsp;
	<b style="font-size:14px">
		Source System: 
	</b>
	<p>
		&nbsp;&nbsp;&nbsp;
		<%= f.text_field :source_system %>
	</p>
	&nbsp;&nbsp;&nbsp;
	<b style="font-size:14px">
		Source Company: 
	</b>
	<p>
		&nbsp;&nbsp;&nbsp;
		<%= f.text_field :source_company %>
	</p>

	<p>
		<%= f.submit "Save changes", , :style => "background-color:#181818;border-radius:15px; display:inline-block; color: white; font-family: Raleway; font-size:15px; padding:14px 30px; text-decoration: none; margin-left: 20%; margin-top: 15px; margin-bottom: 15px; text-align:center;" %>
	<% end %>
</div>

app/views/spends/index.html.erb
<div class="box1">
	<h2>Spends</h2>
	<table>
		<tr>
			<td>
				Start Date <input type="text" id="TxtBx_StartDate" style="width:65px">
			</td>
			<td>
				&nbsp;&nbsp;&nbsp;End Date <input type="text" id="TxtBx_EndDate" style="width:65px">
			</td>
		</tr>
	</table>
	<table>
		<tr>
			<td>
				Recipent Category
				<select>
					<option value="All">All</option>
				</select>
			</td>
			<td>
				&nbsp;&nbsp;&nbsp;Recipent Type
				<select>
					<option value="All">All</option>
				</select>
			</td>
			<td>
				&nbsp;&nbsp;&nbsp;Recipent State
				<%= select_tag :state, options_for_select([
                                "State",
                                "Alabama AL",
                                "Alaska AK",
                                "Arizona AZ",
                                "Arkansas AR",
                                "California CA",
                                "Colorado CO",
                                "Connecticut CT",
                                "Delaware DE",
                                "Florida FL",
                                "Georgia GA",
                                "Hawaii HI",
                                "Idaho ID",
                                "Illinois IL",
                                "Indiana IN",
                                "Iowa IA",
                                "Kansas KS",
                                "Kentucky KY",
                                "Louisiana LA",
                                "Maine ME",
                                "Maryland MD",
                                "Massachusetts MA",
                                "Michigan MI",
                                "Minnesota MN",
                                "Mississippi MS",
                                "Missouri MO",
                                "Montana MT",
                                "Nebraska NE",
                                "Nevada NV",
                                "New Hampshire NH",
                                "New Jersey NJ",
                                "New Mexico NM",
                                "New York NY",
                                "North Carolina NC",
                                "North Dakota ND",
                                "Ohio OH",
                                "Oklahoma OK",
                                "Oregon OR",
                                "Pennsylvania PA",
                                "Rhode Island RI",
                                "South Carolina SC",
                                "South Dakota SD",
                                "Tennessee TN",
                                "Texas TX",
                                "Utah UT",
                                "Vermont VT",
                                "Virginia VA",
                                "Washington WA",
                                "West Virginia WV",
                                "Wisconsin WI",
                                "Wyoming WY" ]),:style => "width:154px" %>
			</td>
		</tr>
	</table>
	<table>
		<tr>
			<td>
				Spend Activity Type
				<select>
					<option value="All">All</option>
					<option value="Call">Call</option>
					<option value="Advisory Board">Advisory Board</option>
				</select>
			</td>
			<td>
				&nbsp;&nbsp;&nbsp;Spend Detail Type
				<select>
					<option value="All">All</option>
					<option value="Lunch">Lunch</option>
					<option value="Travel">Travel</option>
					<option value="Souvenir">Souvenir</option>
					<option value="Meal">Meal</option>
					<option value="Contracted Fee">Contracted Fee</option>
				</select>
			</td>
		</tr>
	</table>
	<table>
		<tr>
			<td>
				Business Purpose
				<select>
					<option value="All">All</option>
					<option vlaue="Promotion">Promotion</option>
				</select>
			</td>
			<td>
			</td>
		</tr>
	</table>
	<table>
		<tr>
			<td>
				<input type="button" id="submit" value="Filter" style=" width:40px;height:35px;background-color:#181818;border-radius:5px; display:inline-block; color: white; font-size:10px;  text-decoration: none; margin-left: 5%; margin-top: 15px; margin-bottom: 15px; text-align:center;">
			</td>
			<td>
			</td>
		</tr>
	</table>
</div>
<br/>
<table class="tablestyle" width="100%">
	<tr>
		<th>
			Spend Id
		</th>
		<th>
		</th>
		<th>
			Transfer of Value Date
		</th>
		<th>
			Spend Activity
		</th>
		<th>
			Spend Detail
		</th>
		<th>
			Business Purpose
		</th>
		<th>
			Amount
		</th>
	</tr>
	<% if @spends.nil? %>
	<tr>
		<td>
			No Spends found.
		</td>
	</tr>
	<% else %>
		<% @spends.each do |s| %>
		<tr>
			<td>
				<%= link_to s.id,s, style: "color: #0099cc;font-weight:bold" %>
			</td>
			<td >
				<%= link_to "Edit",edit_spend_path(s.id),method: :get, style: "color: #0099cc;font-weight:bold" %>
			</td>
			<td>
				<% if !s.DateofPayment.nil? %>
				<%= s.DateofPayment.to_time.strftime('%b %d,%Y') %>
				<% end %>
			</td>
			
		</tr>
		<% end %>
	<% end %>
</table>

app/views/spends/new.html.erb
<h1>Spends#new</h1>
<p>Find me in app/views/spends/new.html.erb</p>

app/views/spends/show.html.erb
<div class="box1">
	<h2>Spends</h2>
	<table>
		<tr>
			<td>
				Start Date <input type="text" id="TxtBx_StartDate" style="width:65px">
			</td>
			<td>
				&nbsp;&nbsp;&nbsp;End Date <input type="text" id="TxtBx_EndDate" style="width:65px">
			</td>
		</tr>
	</table>
	<table>
		<tr>
			<td>
				Recipent Category
				<select>
					<option value="All">All</option>
				</select>
			</td>
			<td>
				&nbsp;&nbsp;&nbsp;Recipent Type
				<select>
					<option value="All">All</option>
				</select>
			</td>
			<td>
				&nbsp;&nbsp;&nbsp;Recipent State
				<%= select_tag :state, options_for_select([
                                "All",
                                "Alabama AL",
                                "Alaska AK",
                                "Arizona AZ",
                                "Arkansas AR",
                                "California CA",
                                "Colorado CO",
                                "Connecticut CT",
                                "Delaware DE",
                                "Florida FL",
                                "Georgia GA",
                                "Hawaii HI",
                                "Idaho ID",
                                "Illinois IL",
                                "Indiana IN",
                                "Iowa IA",
                                "Kansas KS",
                                "Kentucky KY",
                                "Louisiana LA",
                                "Maine ME",
                                "Maryland MD",
                                "Massachusetts MA",
                                "Michigan MI",
                                "Minnesota MN",
                                "Mississippi MS",
                                "Missouri MO",
                                "Montana MT",
                                "Nebraska NE",
                                "Nevada NV",
                                "New Hampshire NH",
                                "New Jersey NJ",
                                "New Mexico NM",
                                "New York NY",
                                "North Carolina NC",
                                "North Dakota ND",
                                "Ohio OH",
                                "Oklahoma OK",
                                "Oregon OR",
                                "Pennsylvania PA",
                                "Rhode Island RI",
                                "South Carolina SC",
                                "South Dakota SD",
                                "Tennessee TN",
                                "Texas TX",
                                "Utah UT",
                                "Vermont VT",
                                "Virginia VA",
                                "Washington WA",
                                "West Virginia WV",
                                "Wisconsin WI",
                                "Wyoming WY" ]),:style => "width:154px" %>
			</td>
		</tr>
	</table>
	<table>
		<tr>
			<td>
				Spend Activity Type
				<select>
					<option value="All">All</option>
					<option value="Call">Call</option>
					<option value="Advisory Board">Advisory Board</option>
				</select>
			</td>
			<td>
				&nbsp;&nbsp;&nbsp;Spend Detail Type
				<select>
					<option value="All">All</option>
					<option value="Lunch">Lunch</option>
					<option value="Travel">Travel</option>
					<option value="Souvenir">Souvenir</option>
					<option value="Meal">Meal</option>
					<option value="Contracted Fee">Contracted Fee</option>
				</select>
			</td>
		</tr>
	</table>
	<table>
		<tr>
			<td>
				Business Purpose
				<select>
					<option value="All">All</option>
					<option vlaue="Promotion">Promotion</option>
				</select>
			</td>
			<td>
			</td>
		</tr>
	</table>
	<table>
		<tr>
			<td>
				<input type="button" id="submit" value="Filter" style=" width:40px;height:35px;background-color:#181818;border-radius:5px; display:inline-block; color: white; font-size:10px;  text-decoration: none; margin-left: 5%; margin-top: 15px; margin-bottom: 15px; text-align:center;">
			</td>
			<td>
			</td>
		</tr>
	</table>
</div>
<br/>

<div class="box1">
	<h2>Spend Description</h2>
	&nbsp;&nbsp;&nbsp;<b style="font-size:14px">Amount: </b><p>&nbsp;&nbsp;&nbsp;<%= @spends.Amount %></p>
	&nbsp;&nbsp;&nbsp;<b style="font-size:14px">Spend Activity: </b><p>&nbsp;&nbsp;&nbsp;<%= @spends.SpendActivity %></p>
	&nbsp;&nbsp;&nbsp;<b style="font-size:14px">Spend Detail: </b><p>&nbsp;&nbsp;&nbsp;<%= @spends.SpendDetail %></p>
	&nbsp;&nbsp;&nbsp;<b style="font-size:14px">Business Purpose: </b><p>&nbsp;&nbsp;&nbsp;<%= @spends.BusinessPurpose %></p>
	&nbsp;&nbsp;&nbsp;<b style="font-size:14px">Spend Description: </b><p>&nbsp;&nbsp;&nbsp;<%= @spends.spend_description %></p>
	&nbsp;&nbsp;&nbsp;<b style="font-size:14px">Spend Date: </b><p>&nbsp;&nbsp;&nbsp;<% if !@spends.Date.nil? %><%= @spends.Date.to_time.strftime('%b %d,%Y') %><% end %></p>
	&nbsp;&nbsp;&nbsp;<b style="font-size:14px">Payment Date: </b><p>&nbsp;&nbsp;&nbsp;<%= @spends.payment_date %></p>
	&nbsp;&nbsp;&nbsp;<b style="font-size:14px">Source System: </b><p>&nbsp;&nbsp;&nbsp;<%= @spends.source_system %></p>
	&nbsp;&nbsp;&nbsp;<b style="font-size:14px">Source Company: </b><p>&nbsp;&nbsp;&nbsp;<%= @spends.source_company %></p>
</div>
