config/routes.rb
PharmaPortal::Application.routes.draw do
  get "search/Search"
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}, via: [:get,:post]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :transfer_of_value
  resources :disputes
  root to: "sessions#new"
  match '/dashboard',to: "static_pages#dashboard", via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/recipients', to: 'transfer_of_value#recipients', :via => :post
  match '/spends', to: 'transfer_of_value#spends', :via => :post
  match '/party',to: 'transfer_of_value#party', :via => :post
  match '/product', to: 'transfer_of_value#product', :via => :post
  match '/updates',to: 'transfer_of_value#updates',:via => :post

  match "/search", to: 'search#Search', :as => :search, :via => :get
  match "/searchDisputes", to: 'search#SearchDisputes',:as => :searchDisputes,:via => :get

end

app/models/transfer_of_value.rb
class TransferOfValue < ActiveRecord::Base
	has_many :recipients
end

app/controllers/transfer_of_value_controller.rb
class TransferOfValueController < ApplicationController
    respond_to :html, :json

    def new
        @physicians = User.where(userType: 'Physician')
        @hospitals = User.where(userType: 'Hospital')
    end

    def create
        @spen=TransferOfValue.new(:paymentName => params[:title],:totalAmount => params[:amount] ,:NatureofPayment => params[:purpose],:form_of_payment => params[:payment_method], :numberofPayment => params[:num_of_pay],:DateofPayment => params[:spend_date],:ActivityType => params[:ActivityType],:DetailType => params[:DetailType])
        @spen.save
        @spend_id=TransferOfValue.last.id

        if params[:RecipientType] == "Physician"
            @rec=RecipientAmount.new(:RecipientID => params[:RecID], :AmountID => @spend_id)
            @rec.save
        else
            @rec=RecipientAmount.new(:RecipientID => params[:RecID1], :AmountID => @spend_id)
            @rec.save
        end
        @party=GeneralRecord.new(:ThirdPartyPayemntRecipientIndicator => params[:Party],:NameofThirdParty => params[:name_of_party],:Charity => params[:charity],:ContextualInformation => params[:info], :AmountID => @spend_id)
        @party.save
        if params[:category] == "Drug or Biological"
            @prod = AssociatedProduct.new(:AmountID => @spend_id, :nameofDrugorBiological => params[:name] )
            @prod.save
        else
            @prod = AssociatedProduct.new(:AmountID => @spend_id, :nameofDeviceorMedicalSupply => params[:name])
            @prod.save
        end

        if params[:product].present?
            params[:product].each_with_index do |(key,name1),k|
                params[:category1].each_with_index do |(key,category1),l|
                    if k == l
                        print "#{name1}"
                        puts ","
                        puts category1

                        if category1 == "Drug or Biological"
                             @prod = AssociatedProduct.new(:AmountID => @spend_id, :nameofDrugorBiological => name1 )
                             @prod.save
                        else
                             @prod = AssociatedProduct.new(:AmountID => @spend_id, :nameofDeviceorMedicalSupply => name1)
                             @prod.save
                        end
                    end
                end
            end
        end

        redirect_to transfer_of_value_path(@spend_id)
    end

    def updates
        @spen=TransferOfValue.find(params[:idSpen])

        @spen.update_attribute(:paymentName,params[:title])
        @spen.update_attribute(:totalAmount,params[:amount])
        @spen.update_attribute(:NatureofPayment,params[:purpose])
        @spen.update_attribute(:numberofPayment,params[:num_of_pay])
        @spen.update_attribute(:DateofPayment,params[:spend_date])
        @spen.update_attribute(:ActivityType,params[:ActivityType])
        @spen.update_attribute(:DetailType,params[:DetailType])

        @party=GeneralRecord.find(params[:idThird])

        @party.update_attribute(:ThirdPartyPayemntRecipientIndicator,params[:Party])
        @party.update_attribute(:NameofThirdParty,params[:name_of_party])
        @party.update_attribute(:Charity,params[:charity])
        @party.update_attribute(:ContextualInformation,params[:info])

        AssociatedProduct.delete_all(:AmountID => params[:idSpend])
        params[:name].each_with_index do |(key,name),i|
            params[:category].each_with_index do |(key,category),j|
                if i == j
                    print "#{name}"
                    puts ","
                    puts category

                    if category == "Drug or Biological"
                         @prod = AssociatedProduct.new(:AmountID => params[:idSpend], :nameofDrugorBiological => name )
                         @prod.save
                    else
                         @prod = AssociatedProduct.new(:AmountID => params[:idSpend], :nameofDeviceorMedicalSupply => name)
                         @prod.save
                    end
                end
            end
        end

        if !params[:product].blank?
            params[:product].each_with_index do |(key,name1),k|
                params[:category1].each_with_index do |(key,category1),l|
                    if k == l
                        print "#{name1}"
                        puts ","
                        puts category1

                        if category1 == "Drug or Biological"
                            @prod = AssociatedProduct.new(:AmountID => params[:idSpend], :nameofDrugorBiological => name1 )
                            @prod.save
                        else
                            @prod = AssociatedProduct.new(:AmountID => params[:idSpend], :nameofDeviceorMedicalSupply => name1)
                            @prod.save
                        end
                    end
                end
            end
        end

        @dispute1=Dispute.where('"AmountID" = ?',  params[:idSpend])
        #@date=Date.strptime params[:DisputeDate], '%m-%d-%Y'
#        @Resdate=Date.strptime params[:ResolveDate], '%m-%d-%Y'
            @dispute1.first.update_attribute(:Status, params[:Status])
            @dispute1.first.update_attribute(:Description, params[:Description])
            @dispute1.first.update_attribute(:DisputeDate, params[:DisputeDate])
            @dispute1.first.update_attribute(:ResolveDate, @Resdate )
            @dispute1.first.update_attribute(:ResolveDescription,params[:FinalComment])
        redirect_to '/disputes'

    end


    def recipients
        puts "id= "+params[:id]
        @rec=Recipient.find(params[:ids])

        @rec.update_attribute(:recipientType,params[:RecipientType])
        if params[:RecipientType] == "Physician"
            @rec.update_attribute(:physicianFirstName,params[:FirstName])
            @rec.update_attribute(:physicianMiddleName,params[:MiddleName])
            @rec.update_attribute(:physicianLastName,params[:LastName])
            @rec.update_attribute(:suffix,params[:Suffix])
            @rec.update_attribute(:businessAddress,params[:address])
            @rec.update_attribute(:city,params[:city])
            @rec.update_attribute(:state,params[:State])
            @rec.update_attribute(:zip,params[:zip])
        else
            @rec.update_attribute(:teachingHospitalName,params[:Hospital])
            @rec.update_attribute(:businessAddress,params[:address])
            @rec.update_attribute(:city,params[:city])
            @rec.update_attribute(:state,params[:State])
            @rec.update_attribute(:zip,params[:zip])
        end
        redirect_to transfer_of_value_path(params[:id])
    end

    def spends

        puts "id= "+params[:id]
        @spen=TransferOfValue.find(params[:id])

        @spen.update_attribute(:paymentName,params[:title])
        @spen.update_attribute(:form_of_payment,params[:payment_method])
        @spen.update_attribute(:totalAmount,params[:amount])
        @spen.update_attribute(:NatureofPayment,params[:purpose])
        @spen.update_attribute(:numberofPayment,params[:num_of_pay])
        @spen.update_attribute(:DateofPayment,params[:spend_date])
        @spen.update_attribute(:ActivityType,params[:ActivityType])
        @spen.update_attribute(:DetailType,params[:DetailType])
        
        redirect_to transfer_of_value_path(params[:id])
    end

    def party
        @party=GeneralRecord.find(params[:ids])

        @party.update_attribute(:ThirdPartyPayemntRecipientIndicator,params[:Party])
        @party.update_attribute(:NameofThirdParty,params[:name_of_party])
        @party.update_attribute(:Charity,params[:charity])
        @party.update_attribute(:ContextualInformation,params[:info])

        redirect_to transfer_of_value_path(params[:id])        
    end

    def product
        AssociatedProduct.delete_all(:AmountID => params[:id])
        params[:name].each_with_index do |(key,name),i|
            params[:category].each_with_index do |(key,category),j|
                if i == j
                    print "#{name}"
                    puts ","
                    puts category

                    if category == "Drug or Biological"
                         @prod = AssociatedProduct.new(:AmountID => params[:id], :nameofDrugorBiological => name )
                         @prod.save
                    else
                         @prod = AssociatedProduct.new(:AmountID => params[:id], :nameofDeviceorMedicalSupply => name)
                         @prod.save
                    end
                end
            end
        end

        params[:product].each_with_index do |(key,name1),k|
            params[:category1].each_with_index do |(key,category1),l|
                if k == l
                    print "#{name1}"
                    puts ","
                    puts category1

                    if category1 == "Drug or Biological"
                         @prod = AssociatedProduct.new(:AmountID => params[:id], :nameofDrugorBiological => name1 )
                         @prod.save
                    else
                         @prod = AssociatedProduct.new(:AmountID => params[:id], :nameofDeviceorMedicalSupply => name1)
                         @prod.save
                    end
                end
            end
        end

        
        #if !params[:parametersSch].blank?
            
        #@Education = Education.new( :UserID => current_user.id, :SchoolName => @degree, :SchoolFrom => @from, :SchoolTo => @to )
       # @Education.save
        redirect_to transfer_of_value_path(params[:id])  
    end

    def edit
        @spends=TransferOfValue.find(params[:id])
        @Recipients=Recipient.where('"AmountID" = ?',params[:id])
        @Products= AssociatedProduct.where('"AmountID" = ?',params[:id])
        @ThirdParty=GeneralRecord.where('"AmountID" = ?', params[:id])
        @dispute=Dispute.where('"AmountID" = ?',params[:id])
    end

    def index
  	   @spends=TransferOfValue.all
    end

app/helpers/transfer_of_value_helper.rb
module TransferOfValueHelper
end

app/views/transfer_of_value/edit.html.erb
<%= form_tag ({controller: "transfer_of_value",:action => :updates, :remote => true}) do |f| %>
	<div class="box1">
		<h2>Spend Description</h2>
		<table>
			<tr>
				<td>
					Title:
				</td>
				<td>
					<input type="text" name="title" id="title" value="<%= @spends.paymentName %>" />
				</td>
			</tr>
			<tr>
				<td>
					Amount: 
				</td>
				<td>
					<input type="text" name="amount" id="amount" value="<%= @spends.totalAmount %>" />
				</td>
			</tr>
			<tr>
				<td>
					Business Purpose: 
				</td>
				<td>
					<input type="text" name="purpose" id="purpose" value="<%= @spends.NatureofPayment %>" />
				</td>
			</tr>
			<tr>
				<td>
					Number of Payments:
				</td>
				<td>
					<input type="text" name="num_of_pay" id="num_of_pay" value="<%= @spends.numberofPayment %>" />
				</td>
			</tr>
			<tr>
				<td>
					Spend Date: 
				</td>
				<td>
					<% if !@spends.DateofPayment.nil? %>
						<input type="text" name="spend_date" id="spend_date" value="<%= @spends.DateofPayment.to_time.strftime('%b %d,%Y') %>" />
					<% else %>
						<input type="text" name="spend_date" id="spend_date" value="" />
					<% end %>
				</td>
			</tr>
			<tr>
				<td>
					Spend Activity Type:
				</td>
				<td>
					<%= select_tag "ActivityType", options_for_select(["All","Call","Advisory Board"], @activity) %>
				</td>
			</tr>
			<tr>
				<td>
					Spend Detail Type:
				</td>
				<td>
					<%= select_tag "DetailType", options_for_select(["All","Lunch","Travel","Souvenir","Meal","Contracted Fee"], @spends.DetailType) %>
				</td>
			</tr>
			<tr> 
				<td>
					<input type="hidden" id="idSpen" name="idSpen" value="<%= @spends.id %>" />
				</td>
			</tr>
		</table>
	</div>
	<br/>
	<script type="text/javascript">

		$("#spend_date").datepicker({
			buttonImageOnly:true,
			buttonImage: 'calendar.jpg',
			dateFormat: 'mm-dd-yy'
		});
		$(document).ready(function() {
		    $("#AddSch").click(function() {
		    	
		    	var rownum=$("#ControlsProd > tbody > tr").length;
		    	//alert(rownum);
		        if (rownum == 0)
		        {
		        	updated_row_num=0;
		        }
		        else 
		        {
		        	updated_row_num=rownum/2;
		        }
                var field = $("#field").val();
                
                var newRow1 = "<tr><td> <input type='button' class='btn_rmvsch' value='Remove'/></td></tr>";
                var input1 = "<input name='product["+ updated_row_num +"]' id='field' type='text' />"
                var newRow = "<tr><td><input type='radio' id='category' "
                +"name='category1["+updated_row_num+"]' value='Drug or Biological' />Drug or Biological"
                +"</td><td><input type='radio' id='category' name='category1["+updated_row_num+"]'"
                +"value='Device or Mdeical Supply'  />Device or Mdeical Supply</td>	</tr>"
                +"<tr><td>" + input1 + "</td></tr>";
                $('#ControlsProd').append(newRow);
                $('#ControlsProd').append(newRow1);
            });
            $('#ControlsProd').on('click', '.btn_rmvsch', function() {
                var index = $(this).closest('tr').index() + 2
                //alert(index);
                $('#ControlsProd tr:nth-child(n+' + (index - 3) + ')').remove();
                return false;
            });
        })
	</script>
	<div class="box1">
		<h2>Products</h2>
		<table>
			<% @Products.each_with_index do |p,i| %>
				<% if p.nameofDrugorBiological.blank? %>
				<tr>
					<td>
						<input type="radio" id="category" name="category[<%= i %>]" 
                    value="Drug or Biological" />Drug or Biological
               		</td>
               		<td>
                   		<input type="radio" id="category" name="category[<%= i %>]" 
                    value="Device or Mdeical Supply" checked />Device or Mdeical Supply
					</td>
				</tr>
				<tr>
					<td>
						Product:
					</td>
					<td>
						<input type="text" name="name[<%= i %>]" value="<%= p.nameofDeviceorMedicalSupply %>" />
					</td>
				</tr>
				<% else %>
				<tr>
					<td>
						<input type="radio" id="category" name="category[<%= i %>]" 
                    value="Drug or Biological" checked />Drug or Biological
               		</td>
               		<td>
               			<input type="radio" id="category" name="category[<%= i %>]" 
                    value="Device or Mdeical Supply"  />Device or Mdeical Supply
					</td>
				</tr>
				<tr>
					<td>
						Product: 
					</td>
					<td>
						<input tye="text" name="name[<%= i %>]" value="<%= p.nameofDrugorBiological %>" />
					</td>
				</tr>
				<% end %>
			<% end %>
			<tr>
				<td>
					<input type="button" name="AddSch" id="AddSch" Value="Add" />
					<input type="hidden" id="idSpend" name="idSpend" value="<%= @spends.id %>" />
				</td>
			</tr>
		</table>
		<table id="ControlsProd">
		</table>
	</div>
	<br/>
	<div class="box1">
		<h2>3rd Party Payee</h2>
		<table>
			<tr>
				<td>
					3rd Party Indicatror: 
				</td>
				<td>
					<select name="Party" id="Party"  >
						<% if @ThirdParty.first.ThirdPartyPayemntRecipientIndicator== "Entity" %>
							<option value="Entity" selected >Entity</option>
							<option value="Individual" >Individual</option>
							<option value="No Third Party">No Third Party</option>
						<% elsif @ThirdParty.first.ThirdPartyPayemntRecipientIndicator == "Individual" %>
							<option value="Entity">Entity</option>
							<option value="Individual" selected>Individual</option>
							<option value="No Third Party">No Third Party</option>
						<% else %>
							<option value="Entity">Entity</option>
							<option value="Individual" >Individual</option>
							<option value="No Third Party" selected>No Third Party</option>
						<% end %>
					</select>
				</td>
			</tr>
			<tr>
				<td>
					Name of 3rd Party Entity: 
				</td>
				<td>
					<input type="text" name="name_of_party" id="name_of_party" value="<%= @ThirdParty.first.NameofThirdParty %>" />
				</td>
			</tr>
				<tr>
					<td>
   						Charity: 
					</td>
					<td>
						<input type="text" name="charity" id="charity" value="<%= @ThirdParty.first.Charity %>" />
					</td>
				</tr>
				<tr>
					<td>
						Information: 
					</td>
					<td>
						<input type="text" name="info" id="info" value="<%= @ThirdParty.first.ContextualInformation %>" />
					</td>
				</tr>
				<tr>
					<td>
						<input type="hidden" id="idThird" name="idThird" value="<%= @ThirdParty.first.id %>" />
					</td>
				</tr>
		</table>
	</div>
	<br/>
	<div class="box1">
		<h2>Dispute</h2>
		<table>
			<tr>
				<td>
					Dispute
				</td>
				<td>
					<select name="Status" id="Status"  >
						<% if @dispute.first.Status == "Open" %>
							<option value="Open" selected >Open</option>
							<option value="Dispute" >Dispute</option>
							<option value="Resolved">Resolved</option>
						<% elsif @dispute.first.Status == "Dispute" %>
							<option value="Open" >Open</option>
							<option value="Dispute" selected >Dispute</option>
							<option value="Resolved">Resolved</option>
						<% else %>
							<option value="Open" >Open</option>
							<option value="Dispute" >Dispute</option>
							<option value="Resolved" selected >Resolved</option>
						<% end %>
					</select>
				</td>
			</tr>
			<tr>
				<td>
					Descripion
				</td>
				<td>
					<input type="text" name="Description" id="Descrption" value="<%= @dispute.first.Description %>" />
				</td>
			</tr>
			<tr>
				<td>
					Date: 
				</td>
				<td>
					<% if !@dispute.first.DisputeDate.nil? %>
						<input type="text" name="DisputeDate" id="DisputeDate" value="<%= @dispute.first.DisputeDate.to_time.strftime('%b %d,%Y') %>" />
					<%end %>
				</td>
			</tr>
			<tr>
				<td>
					Resolving Date: 
				</td>
				<td>
					<% if !@dispute.first.ResolveDate.nil? %>
						<input type="text" name="ResolveDate" id="ResolveDate" value="<%= @dispute.first.ResolveDate.to_time.strftime('%b %d,%Y') %>" />
					<%else %>
						<input type="text" name="ResolveDate" id="ResolveDate" value="" />
					<% end %>
				</td>
			</tr>
			<tr>
				<td>
					Resolving Comments:
				</td>
				<td>
					<input type="text" name="FinalComment" id="FinalComment" value="<%= @dispute.first.ResolveDescription %>" />
				</td>
			</tr>
		</table>
	</div>
	<br/>
	<%= submit_tag 'Update' %>
<%end%>
<script type="text/javascript">
	$("#ResolveDate").datepicker({
			buttonImageOnly:true,
			buttonImage: 'calendar.jpg',
			dateFormat: 'mm-dd-yy'
		});
	$("#DisputeDate").datepicker({
			buttonImageOnly:true,
			buttonImage: 'calendar.jpg',
			dateFormat: 'mm-dd-yy'
		});
</script>

app/views/transfer_of_value/index.html.erb
<% if !current_user.nil? %>
<% if current_user.userType =="Employee" %>
<%= link_to "Create New Spend", new_transfer_of_value_path, :style => "background-color:#181818;border-radius:10px; display:inline-block; color: white; font-family: Raleway; font-size:12px; padding:8px 18px; text-decoration: none; margin-top: 15px; margin-bottom: 15px; text-align:center;" %>
<% end %>
<% end %>

<form action='<%= search_path %>' method='get'>
<div class="box1">
	<h2>Spends</h2>
	<table>
		<tr>
			<td>
				Start Date <input type="text" name="Start" id="TxtBx_StartDate" style="width:65px">
			</td>
			<td>
				&nbsp;&nbsp;&nbsp;End Date <input type="text" name="End" id="TxtBx_EndDate" style="width:65px">
			</td>
		</tr>
	</table>
	<script type="text/javascript">
		$('#TxtBx_StartDate').datepicker({
			buttonImageOnly: true,
			buttonImage: 'calendar.jpg',
			dateFormat: 'mm-dd-yy'
		});
		$('#TxtBx_EndDate').datepicker({
			buttonImageOnly: true,
			buttonImage: 'calendar.jpg',
			dateFormat: 'mm-dd-yy'
		});
	</script>
	<table>
		<tr>
			<!--<td>
				Recipent Category
				<select>

				</select>
			</td>-->
			<td>
				Recipent Type
				<select name='UserType'>
					<option value="All">All</option>
					<option value="Physician">Physician</option>
					<option value="Hospital">Hospital</option>
				</select>
			</td>
			<td>
				&nbsp;&nbsp;&nbsp;Recipent State
				<%= select_tag :State, options_for_select([
                                "All",
                                "Alabama AL",
                                "Alaska AK",
                                "Arizona AZ",
                                "Arkansas AR",
                                "California CA",
                                "Colorado CO",
                                "Connecticut CT",
                                "Delaware DE",
                                "Florida FL",
                                "Georgia GA",
                                "Hawaii HI",
                                "Idaho ID",
                                "Illinois IL",
                                "Indiana IN",
                                "Iowa IA",
                                "Kansas KS",
                                "Kentucky KY",
                                "Louisiana LA",
                                "Maine ME",
                                "Maryland MD",
                                "Massachusetts MA",
                                "Michigan MI",
                                "Minnesota MN",
                                "Mississippi MS",
                                "Missouri MO",
                                "Montana MT",
                                "Nebraska NE",
                                "Nevada NV",
                                "New Hampshire NH",
                                "New Jersey NJ",
                                "New Mexico NM",
                                "New York NY",
                                "North Carolina NC",
                                "North Dakota ND",
                                "Ohio OH",
                                "Oklahoma OK",
                                "Oregon OR",
                                "Pennsylvania PA",
                                "Rhode Island RI",
                                "South Carolina SC",
                                "South Dakota SD",
                                "Tennessee TN",
                                "Texas TX",
                                "Utah UT",
                                "Vermont VT",
                                "Virginia VA",
                                "Washington WA",
                                "West Virginia WV",
                                "Wisconsin WI",
                                "Wyoming WY" ]) %>
			</td>
		</tr>
	</table>
	<table>
		<tr>
			<td>
				Spend Activity Type
				<select name="ActivityType">
					<option value="All">All</option>
					<option value="Call">Call</option>
					<option value="Advisory Board">Advisory Board</option>
				</select>
			</td>
			<td>
				&nbsp;&nbsp;&nbsp;Spend Detail Type
				<select name="DetailType">
					<option value="All">All</option>
					<option value="Lunch">Lunch</option>
					<option value="Travel">Travel</option>
					<option value="Souvenir">Souvenir</option>
					<option value="Meal">Meal</option>
					<option value="Contracted Fee">Contracted Fee</option>
				</select>
			</td>
		</tr>
	</table>
	<table>
		<tr>
			<td>
				Business Purpose
				<select name="NatureOfPayment">
					<option value="All">All</option>
					<option vlaue="Promotion">Promotion</option>
				</select>
			</td>
			<td>
			</td>
		</tr>
	</table>
	<table>
		<tr>
			<td>
				<input type="submit" value="Filter" style=" width:40px;height:35px;background-color:#181818;border-radius:5px; display:inline-block; color: white; font-size:10px;  text-decoration: none; margin-left: 5%; margin-top: 15px; margin-bottom: 15px; text-align:center;">
			</td>
			<td>
			</td>
		</tr>
	</table>
</div>
</form>
<br/>
<table class="tablestyle" width="100%">
	<tr>
		<th>
			Spend Id
		</th>
		
		<th>
			Transfer of Value Date
		</th>
		<th>
			Amount
		</th>
		<th>
			Number of Payments
		</th>
		<th>
			Nature of Payment
		</th>
		
	</tr>
	<% if @spends.nil? %>
	<tr>
		<td>
			No Spends found.
		</td>
	</tr>
	<% else %>
		<% @spends.each do |s| %>
		<tr class="<%= cycle("odd", "even") %>" >
			<td>
				<%= link_to s.id,s, style: "color: #0099cc;font-weight:bold" %>
			</td>
			<td>
				<% if !s.DateofPayment.nil? %>
				<%= s.DateofPayment.to_time.strftime('%b %d,%Y') %>
				<% end %>
			</td>
			<td>
				<%= s.totalAmount %>
			</td>
			<td>
				<%= s.numberofPayment %>
			</td>
			<td>
				<%= s.NatureofPayment %>
			</td>
			
		</tr>
		<% end %>
	<% end %>
</table>